### ISSUE TITLE
downloadで途中で切断された場合に正常終了してしまう

### ISSUE THREAD

**Issue by mei23** [mei23/misskey#1020]
## 💡 Summary
```ts
import * as net from  'net';

const server = net.createServer(c => {
	console.log(`client connected: ${c.remoteAddress}:${c.remotePort}`);

	c.on('data', data => {
		console.log(data + ' from ' + c.remoteAddress + ':' + c.remotePort);
		c.write(`HTTP/1.0 200 OK\r\n`);
		c.write(`Content-Length: 10\r\n`);
		c.write(`\r\n`);
		c.write(`aaa`);
		c.destroy();
	});

	c.on('end', () => {
		console.log('client disconnected');
	});
}).listen(3331);

console.log('listening on port 3331');
```
みたいな10バイトあるはずが3バイトしか送らないで切断しても
3バイトのファイルをDLして正常終了してしまう。

note-fetchだけではなくrequestのバージョンでも起こる

## 📝 Steps to Reproduce

1.
2.
3.

**Comment by u1-liquid** [comment]
https://tools.ietf.org/html/rfc7230#section-3.4

> A message that uses a valid Content-Length is incomplete if the size of the message body received (in octets) is less than the value given by Content-Length. A response that has neither chunked transfer coding nor Content-Length is terminated by closure of the connection and, thus, is considered complete regardless of the number of message body octets received, provided that the header section was received intact.

えー

**Comment by mei23** [comment]
↑たぶん特に変な事は書いてないです

1
```
Content-Length: 10
```
だったら10バイト受信したら正常終了すればいい

2
```
Content-Length: なし
Transfer-Encoding: chunked
```
だったら応答終了をマークするchunkを受信できたら正常終了すればいい

3
```
Content-Length: なし
Transfer-Encoding: なし
```
なら接続断を検知したら正常終了とすればいい

って意味でほとんどのサーバーは1, 2のいずれかなので問題ないです。

---

今問題になってるのは、
1, 2 であきらかに受信したものが足りなくても、response stream で error イベントが上がらないので、enexcepted closeが検知できないという点です。

**Comment by mei23** [comment]
これ `request`でも`node-fetch`でも`got`でも`axios`でも`superagent`でも起きるので、ハンドル無理かも。

**Comment by mei23** [comment]
`HTTP/1.0`で送り出すようにすれば`Content-Length`付けてくれる可能性が高くなるので、
それで`Content-Length`あったらDL後に比較するとかすればましになるかも。

**Comment by mei23** [comment]
とりあえずこんな感じ？
https://github.com/mei23/newreq/blob/6362fa1dfe97d07ee95f4ac967aa18c28a666f40/src/dl.ts#L1

HTTP/1.0を指定する方法はなさそうだった

**Comment by mei23** [comment]
とりあえずContent-Lengthが取得できたら比較することに
https://github.com/mei23/misskey/commit/8ae4911511d04a3d541c01af5fc14f5498eca568
https://github.com/mei23/misskey/commit/65999037b667225b93c52c6729c0a124f1d9e73d

**Comment by mei23** [comment]
Node http で、socket, request, response の error インベントlistenしてもerrorなんて起きなかった。
自分でsocket喋るしかない？

**Comment by mei23** [comment]
Node http で aborted イベントをListenすればいいみたい
https://github.com/mei23/newreq/blob/bcd2d9bbef757d80f524e0334e111a0539ee19be/src/http.ts#L51

でも request も node-fetch も対応してない様子

**Comment by mei23** [comment]
gotがちゃんとしてるみたい
