### ISSUE TITLE
ナビゲーションバーの位置が中央以外の場合に検索機能が使用できない

### ISSUE THREAD

**Issue by tkmrgit** [mei23/misskey#1185]
## 💡 Summary

設定からナビゲーションバーの位置を中央以外(左/右)にすると検索機能を使用することができなくなってしまいます。

P.S. この改修をmei23/misskey-v11にもして頂けると非常に喜びます🥳

## 📝 Steps to Reproduce

1.設定を開き、ナビゲーションバーの位置を中央以外に設定する
2.左または右に変更されたナビゲーションバーに検索機能を使用するためのボタンが表示されず、実質使用不可能になる

## 📌 Environment

v10.102.231-m544 
v11

**Comment by mei23** [comment]
mei-m544: https://github.com/mei23/misskey/commit/423ad52cb071d1e32ae1374a4ce99a2e3c1fe6ad
misskey-v11: https://github.com/mei23/misskey-v11/commit/ece6c6bc006cb40a88366c1b3fbed769498a77d0
