### ISSUE TITLE
Safari, WKWebView: 認証画面前のログインフォームにてカーソル位置が暴発する

### ISSUE THREAD

**Issue by YuigaWada** [mei23/misskey#1247]
## 💡 Summary
認証画面前のログインフォームにてカーソル位置が暴発する

https://github.com/mei23/misskey/blob/mei-m544/src/client/app/common/views/components/ui/input.vue#L206

<img src="https://s3.arkjp.net/misskey/1cbce47a-8add-45b3-af67-9aa3520ac463.png">

## 🙂 Expected Behavior
適切なカーソル位置を設定する必要がある

## ☹️ Actual Behavior
認証画面前のログインフォームにてカーソル位置が暴発する。

## 📓Memo

おそらくpaddingを指定している[この部分](https://github.com/mei23/misskey/blob/mei-m544/src/client/app/common/views/components/ui/input.vue#L206)が原因だと思います。

<br>

↓

<br>

SafariやWebViewではこんな感じで
<img src="https://s3.arkjp.net/misskey/ade3802d-a638-4985-bba2-783b3924b53a.png">
Chromeではこんな感じです。
<img src="https://s3.arkjp.net/misskey/3e7606a5-9608-425b-9720-ea1205dab6fb.png">

Chromeでは再現できないので、iOSのSafari, WebView特有の問題だと思われます。

## 📝 Steps to Reproduce

1. API叩いて認証urlを取得する
2. iOSのSafari等で開く
3.

## 📌 Environment
iPhone X: iOS 12.4

**Comment by mei23** [comment]
https://github.com/syuilo/misskey/issues/3839

**Comment by mei23** [comment]
v11のUIだと起きないみたいなので、とりあえず色以外をv11に寄せて（戻して？）みた
10.102.239-m544 以降
