### ISSUE TITLE
ドライブ容量の表記ががペタバイトに対応してない

### ISSUE THREAD

**Issue by mei23** [mei23/misskey#1280]
## 💡 Summary
ドライブ容量の表記ががペタバイトに対応してない
あと小数第2位とかまでほしい

## 📝 Steps to Reproduce

1.
2.
3.

**Comment by tamaina** [comment]
numeral.js導入しようぜ

**Comment by mei23** [comment]
なんかいまいち入れるほどでも

**Comment by tamaina** [comment]
> 消してしまった投稿: numeral.js入れようぜ  

（mei23でびっくりしたので消してしまった）

まあそれはそう

**Comment by mei23** [comment]
微妙にめんどくさいからライブラリ使いたくなってきたわ
https://github.com/mei23/misskey/blob/aadd5b95b811dbd9d0fce9e622613a148e4ad7da/src/client/app/common/views/filters/bytes.ts
