### ISSUE TITLE
eslintでシングルクォーテーションの強制ができない

### ISSUE THREAD

**Issue by mei23** [mei23/misskey#1526]
## 💡 Summary
シングルを強制するとバッククォートもダメと言われる

## 📝 Steps to Reproduce

1.
2.
3.

**Comment by mei23** [comment]
ルールマイグレーションしてみたけどうごかない

**Comment by mei23** [comment]
https://github.com/mei23/misskey/commit/b3f501c6fa94c57140c3bd9be0b104ba65110ad0

**Comment by acid-chicken** [comment]
[allowTemplateLiterals](https://eslint.org/docs/rules/quotes#allowtemplateliterals) つきでもダメだった感じかしら

**Comment by mei23** [comment]
なるほど
