### ISSUE TITLE
ホームでスクロール後に絵文字パレットを表示すると位置が変

### ISSUE THREAD

**Issue by mei23** [mei23/misskey#159]
## Steps to Reproduce

1.
2.
3.

**Comment by acid-chicken** [comment]
position が fixed なので、 absolute にしてやるといい感じになると思います。（twista ではそうしてる）

**Comment by mei23** [comment]
alt
https://misskey.m544.net/notes/5ca090f82f76c34dcdbb2dd8

**Comment by mei23** [comment]
85636b3359020b4facf9815b3ab8aa7b668dd207 で修正
