### ISSUE TITLE
_misskey_content の廃止

### ISSUE THREAD

**Issue by mei23** [mei23/misskey#1838]
## Summary
MisskeyのMFMの生データをそのままやり取りするフィールド
もはや互換のない内部データがやり取りされるだけで意味がない
他のAP実装と同じようにHTML版を使用したほうがマシ

**Comment by mei23** [comment]
_misskey_content を廃止して、content (ActivityPub用 HTML) をこんな感じにする
[HTML5のカスタムデータ属性](https://developer.mozilla.org/ja/docs/Web/HTML/Global_attributes/data-*) を使う
```html
<span data-mfm-name="spin" data-mfm-args="x,left,speed=1.5s">b</span> とか
<span data-mfm-name="spin" data-mfm-x="1" data-mfm-direction="left" data-mfm-speed="1.5s">b</span> とか
<!-- 将来的にMisskey MFM側の表現能力が上がったときに構文を壊さなくていいように最初から下のにしとくのがいいかも -->
```
- _misskey_content と content 両方送らなくて済む
- 未対応実装でゴミが生成されずにスッキリ無視してくれる
- Misskeyでは表現できないタイプのネストも表現できる
- HTML5の標準仕様なので、通常のHTML (JS, CSS) パーサーで楽に扱える

また、現行のクライアント部分ではstyle属性を文字列連結しているが、
`data-*`は、[CSSの属性セレクタが使える](https://developer.mozilla.org/ja/docs/Learn/HTML/Howto/Use_data_attributes#CSS_access) ので、クライアント側でMFM→DOMにする時に`data-*`を使うことにより、文字列連結をいくつか置き換えられるかも。
CSSインジェクションの危険も下がるかも。

また、APIでクライアント向けに返すものにtext (MFM)だけではなくhtmlも追加すると
MastodonではコンテンツをHTMLで返しているので、サードパーティーアプリでパーサー部分が流用できて実装が楽になるかも。

**Comment by Johann150** [comment]
I think https://github.com/misskey-dev/misskey/pull/8787 will be relevant here because `_misskey_content` is deprecated by it.
