### ISSUE TITLE
ユーザーごとのリノート非表示設定

### ISSUE THREAD

**Issue by ne-moni** [mei23/misskey#205]
## Summary
外部とのやり取り上仕方ないかもしれないが、投稿して間もないPostを頻繁にRenoteする人がいるので
Twitterのリツイートを非表示にする設定のように、ユーザーを個別で指定しRenoteをミュートにする設定がほしい

**Comment by mei23** [comment]
けっこうたいへん

**Comment by mei23** [comment]
https://github.com/mei23/misskey/commit/a5fb2417fff37587ff10d298fdb3af8930e0bb34

**Comment by mei23** [comment]
実装済み
