### ISSUE TITLE
CIで動作チェック

### ISSUE THREAD

**Issue by mei23** [mei23/misskey#2071]
## Summary
GitHub Actions で Misskey+MongoDB+Redis を使って実際に動くかチェック

**Comment by syuilo** [comment]
いわゆるスモークテスト的なやつかな

**Comment by mei23** [comment]
@syuilo そんなもんだけど、すでにv11/v12あたりには入ってるはず (PostgreSQLで)

**Comment by mei23** [comment]
v10あたりでもGitHub Actions 以外の部分はあったけど
隔離されたDB/Redisとtest.yml用意しないとローカルでテスト動かせないのがめんどくさくて、その部分消しちゃったんだわ。
