### ISSUE TITLE
yarnやめる？

### ISSUE THREAD

**Issue by mei23** [mei23/misskey#4329]
## Summary
https://github.com/TeamBlackCrystal/ayuskey/issues/289

**Comment by sousuke0422** [comment]
これが発生するのはyarn@2以降(かつpnpmモード？)だからここじゃなくて本家のほうが問題が発生するかも

**Comment by mei23** [comment]
これってこれかしら？
https://github.com/TeamBlackCrystal/ayuskey/issues/136

re2とかsharpとか、node_modules にバイナリとかを投下するモジュールが
ほかのdependenciesをいじったときに壊れちゃうのは yarn v1 から起きるはずだわ。
https://github.com/uhop/node-re2/wiki/Problem:-unusual-errors-with-yarn
(yarn v1なら yarn install --force でなおる、v2/v3で起きたら詰み？)

別事象ではある？

**Comment by mei23** [comment]
- yarn v1 からたまにおかしくなる事象はある。→これは回避できてた。
  その事象はv3あたりでも起きてそう。→でも回避が難しくなってそう。
- `yarn@2`以降(かつpnpmモード？) とかだと、別の問題も出てきそう。

だから、yarn v1のままいれば問題ないけど変えたいなら他の方がいい感じ。

**Comment by mei23** [comment]
- yarn v1 からたまにおかしくなる事象はある。→これは回避できてた。
  その事象はv3あたりでも起きてそう。→でも回避が難しくなってそう。
- `yarn@2`以降(かつpnpmモード？) とかだと、別の問題も出てきそう。

だから、yarn v1のままいれば問題ないけど変えたいなら他の方がいい感じ。

**Comment by sousuke0422** [comment]
速度を重視するなら変えたほうがいいのだわ。windows以外なら確実に高速化するわね。
