### ISSUE TITLE
APIのリクエスト方法(websocket/HTTP)によって返ってくるエラーの内容に違いがある

### ISSUE THREAD

**Issue by marihachi** [mei23/misskey#648]
## 💡 Summary
以下は`notes/create`エンドポイントにパラメータ無しでリクエストした場合のレスポンス
```
http response:
{ error:
   { message: 'Content required. You need to set text, fileIds, renoteId or poll.',
     code: 'CONTENT_REQUIRED',
     id: '6f57e42b-c348-439b-bc45-993995cc515a',
     kind: 'client' } }
websocket response:
{ e:
   { code: 'CONTENT_REQUIRED',
     id: '6f57e42b-c348-439b-bc45-993995cc515a',
     kind: 'client' } }
```

## インスタンスバージョン
10.102.126-m544

本家由来の問題であれば、そちらにissueを立て直します。

**Comment by acid-chicken** [comment]
本流の問題だったとしても、WebSocket からのリクエストは本流では廃止されているので……。

**Comment by mei23** [comment]
それ、WebSocket経由のリクエストは廃止されてるはず

**Comment by acid-chicken** [comment]
ちなみに廃止された理由はサーバーへの負荷が偏るからです。そのため、めい鯖に対しての利用も個人的には推奨はしません。

**Comment by mei23** [comment]
あードキュメントだけ残ってるかも

**Comment by marihachi** [comment]
ドキュメント読んでやってた

**Comment by marihachi** [comment]
廃止されたことを明文化できませんか

**Comment by mei23** [comment]
v11にもドキュメントだけ残ってる

**Comment by marihachi** [comment]
明文化の件は別で立てます。
今回の件は解決ということで。

**Comment by mei23** [comment]
> ちなみに廃止された理由はサーバーへの負荷が偏るからです。そのため、めい鯖に対しての利用も個人的には推奨はしません。

10.78.0 で廃止されていたのでもう使える場所はないと思います。

**Comment by syuilo** [comment]
> WebSocket からのリクエストは本流では廃止されているので……。

廃止はしてないです

**Comment by mei23** [comment]
https://github.com/syuilo/misskey/blob/develop/CHANGELOG.md#10780

> クライアントのAPIリクエストをストリーム経由で行うオプションを廃止

ではなく？！

**Comment by marihachi** [comment]
なんも分からんになった

**Comment by marihachi** [comment]
非推奨という認識は正しい？

**Comment by syuilo** [comment]
サーバーはWebSocket からのAPIリクエストを普通に受け付けます
サードパーティアプリのためにメンテナンスは続けているので、「APIのリクエスト方法(websocket/HTTP)によって返ってくるエラーの内容に違いがある」は普通にバグです

> 非推奨という認識は正しい？

まだ特に決まってないです

**Comment by mei23** [comment]
10.78.0 ではサーバー側のコードは廃止されていなかった
https://github.com/syuilo/misskey/issues/3911

**Comment by marihachi** [comment]
このバグに関してのissueも本家リポに立てておきます。
